#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org
#this should go in /etc/init.d/
START=99

start() {
	/usr/bin/serve-leases.sh
}

stop() {
	killall -9 serve-leases.sh > /dev/null
	killall -9 ncat > /dev/null
}
